name: work place
on:
  issues:
    types: labeled
jobs:
  build:
#    runs-on: ubuntu-20.04
    runs-on: ubuntu-latest
#    runs-on: ubuntu-18.04
#    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "install depends"
      run: |
        sudo apt-get update 
        sudo apt-get install -y p7zip-full unzip
    - name: "startsimpl"
      if: contains(github.event.label.name, 'tsunamiBaseWork')      
      run: |
        sudo ifconfig
        bash -c tsunamiFirstWorkPlace/quick_start.sh
