name: work place
on:
  issues:
    types: labeled
jobs:
  build:
#    runs-on: ubuntu-20.04
    runs-on: ubuntu-latest
#    runs-on: ubuntu-18.04
#    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "install depends"
      run: |
        sudo apt-get update 
        sudo apt-get install -y p7zip-full unzip
    - name: "tsunamiBaseWork"
      if: contains(github.event.label.name, 'tsunamiBaseWork')      
      run: |
        chmod +x ./quick_start.sh
        chmod +x workData/build_all.sh 
        bash -c ./quick_start.sh
