name: work place
on:
  issues:
    types: labeled
jobs:
  build:
#    runs-on: ubuntu-20.04
    runs-on: ubuntu-latest
#    runs-on: ubuntu-18.04
#    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "clean disk"
      run: |
       df -h
       echo "Listing 100 largest packages"
       dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
       df -h
       echo "Removing large packages"
       sudo apt-get remove -y '^liblldb-1*'
       sudo apt-get remove -y '^dotnet-.*'
       sudo apt-get remove -y '^llvm-.*'
       sudo apt-get remove -y 'php.*'
       sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
       sudo apt-get autoremove -y
       sudo apt-get clean
       df -h
       echo "Removing large directories"
       # deleting 15GB
       rm -rf /usr/share/dotnet/
       df -h
       echo "swap and docker images"
       sudo swapoff -a
       sudo rm -f /swapfile
       docker rmi $(docker image ls -aq)
       df -h
    - name: "install depends"
      run: |
        sudo apt-get update 
        sudo apt-get install -y p7zip-full unzip nmap ncrack
    - name: "build plagins and tsunami"
#      if: contains(github.event.label.name, 'tsunamiBaseWork')      
      run: |
        chmod +x ./quick_start.sh
        sudo bash -c ./quick_start.sh
        ls -al /home/runner/tsunami/plugins/
    - name: "docker 1 run"
      run: |
        docker rm $(docker ps -a -q)
        docker stop $(docker ps -a -q)
        docker rmi $(docker image ls -aq)
        docker pull thisvul/weblogic14cjdk8u
        docker run -d -p 7001:7001 --name weblogic14cjdk8u thisvul/weblogic14cjdk8u
        cd /root/tsunami && java -cp "tsunami-main-0.0.10-SNAPSHOT-cli.jar:/root/tsunami/plugins/*" -Dtsunami-config.location=/root/tsunami/tsunami.yaml com.google.tsunami.main.cli.TsunamiCli --ip-v4-target=127.0.0.1 --scan-results-local-output-format=JSON --scan-results-local-output-filename=/tmp/tsunami-output.json    
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tsunamiOutput
        path: /tmp/tsunami-output.json
